# Generated by Django 3.2.13 on 2022-07-16 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('calories', models.IntegerField(blank=True, default=0, verbose_name='Calories')),
                ('fat', models.FloatField(blank=True, default=0, verbose_name='Fat (g)')),
                ('carbs', models.IntegerField(blank=True, default=0, verbose_name='Carbs (g)')),
                ('protein', models.FloatField(blank=True, default=0, verbose_name='Protein (g)')),
                ('iron', models.CharField(blank=True, max_length=4, verbose_name='Iron (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False, verbose_name='連番')),
                ('name', models.CharField(max_length=4, verbose_name='名前')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='部屋名')),
                ('sente_id', models.IntegerField(blank=True, null=True, verbose_name='対局者_先手Id')),
                ('gote_id', models.IntegerField(blank=True, null=True, verbose_name='対局者_後手Id')),
                ('board', models.CharField(max_length=9, verbose_name='盤面')),
                ('record', models.CharField(max_length=9, verbose_name='棋譜')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_state', models.IntegerField(blank=True, default=0, null=True, verbose_name='対局のマッチング状態')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
