# Generated by Django 3.2.14 on 2022-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consecutive_name_vol1o0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVolume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('event_id', models.IntegerField(blank=True, default=0, verbose_name='催事種別Id')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='名称')),
                ('name_s', models.CharField(blank=True, max_length=16, null=True, verbose_name='名称_短縮')),
                ('sort', models.IntegerField(blank=True, default=0, verbose_name='順番')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='display_name',
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_s',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='名称_短縮'),
        ),
    ]
