# Generated by Django 3.2.14 on 2022-09-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consecutive_name_vol1o0', '0002_auto_20220904_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sort',
            field=models.FloatField(blank=True, default=0, verbose_name='順番'),
        ),
        migrations.AlterField(
            model_name='eventvolume',
            name='sort',
            field=models.FloatField(blank=True, default=0, verbose_name='順番'),
        ),
    ]
