# Generated by Django 3.2.13 on 2022-07-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False, verbose_name='連番')),
                ('name', models.CharField(max_length=4, verbose_name='名前')),
            ],
        ),
    ]
