# Generated by Django 3.2.13 on 2022-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='部屋名')),
                ('sente_id', models.IntegerField(blank=True, null=True, verbose_name='対局者_先手Id')),
                ('gote_id', models.IntegerField(blank=True, null=True, verbose_name='対局者_後手Id')),
                ('board', models.CharField(max_length=9, verbose_name='盤面')),
                ('record', models.CharField(max_length=9, verbose_name='棋譜')),
            ],
        ),
    ]
